__title__ = "betfairlightweight"
__description__ = "Lightweight python wrapper for Betfair API-NG"
__url__ = "https://github.com/liampauling/betfair"
__version__ = "0.0.0b22"
__author__ = "Liam Pauling"
__license__ = "MIT"
