__title__ = "betfairlightweight"
__description__ = "Lightweight python wrapper for Betfair API-NG"
__url__ = "https://github.com/betcode-org/betfair"
__version__ = "2.19.0"
__author__ = "Liam Pauling"
__license__ = "MIT"
